/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lzl_Sensor */

#ifndef _Included_lzl_Sensor
#define _Included_lzl_Sensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lzl_Sensor
 * Method:    get_wd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lzl_Sensor_get_1wd
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
